[build]
  publish = "dist/dsw-frontend"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://handsome-integrity-production.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
